---
title: "R Notebook"
output: html_notebook
---

# LOAD LIBRARIES


```{r}
library(sf)
library(tidyverse)
library(leaflet)
library(shiny)
library(lubridate)
library(grid) #needed for custom annotation
```


# Load plot theme and function to prepare plot

```{r}
source(here::here("palette_theme/define_theme.R"))
source(here::here("palette_theme/plot_timeseries.R"))
source(here::here("palette_theme/plot_timeseriesv2.R"))
palette = read_csv(here::here("palette_theme/phs_palette.csv"))
```


# HEALTH BOARD NAMES

```{r}
health_board_list <- read_csv(here::here("lookup_tables/health_board_codes.csv")) %>% 
  janitor::clean_names() %>% 
  distinct(hb_name) %>% 
  pull()
```


# A&E WAITING TIMES

```{r}
waiting_times <- read_csv(here::here("clean_data/a_and_e_data_clean.csv")) %>% 
  janitor::clean_names()

```

#CLEANING SCRIPT









```{r}
# Adding percent meeting target column to dataframe
waiting_times <- waiting_times %>% 
  mutate(percent_meeting_target = number_meeting_target_aggregate / 
           number_of_attendances_aggregate * 100)  


```


```{r}
# A&E Waiting Times    
 #  output$a_and_e_waiting_times <- renderPlot({
     
avg_2018_2019 <- waiting_times %>% 
     filter(month_ending >= "2018-01-01" & month_ending <= "2019-12-31") %>% 
       filter(department_type %in% input$minor_or_emerg_dept) %>% 
       filter(hb_name == input$health_board) %>% 
#     filter(hb_name == "NHS Highland") %>% 
#     filter(patient_type %in% c("New Outpatient, "Inpatient/Day case") %>%      
#     group_by(date) %>% 
     summarise(num_waiting_2018_2019 = sum(number_waiting, na.rm = TRUE)) %>% 
     summarise(avg_num_waiting = mean(avg_num_waiting_2018_2019)) 




    waiting_times %>% 
       # Conduct this 2020 filtering step at an earlier stage
       filter(date >= "2020-01-01") %>% 
       filter(department_type %in% input$minor_or_emerg_dept) %>% 
       filter(hb_name == input$health_board) %>% 
       group_by(date) %>% 
       summarise(percent_meeting_target_by_month = mean(percent_meeting_target)) %>% 
       
       timeseriesplot(aes(date, percent_meeting_target_by_month),
                      "Percentage of Attendances Meeting 4 Hour Target", 
                      "% Meeting 4 Hour Target") +
       labs(subtitle = "Data Averaged By Month") +
       theme(axis.text = element_text(size = 12)) +
       # Make sure only whole percent number shows on y-axis (not e.g. 92.5%)
       scale_y_continuous(labels = scales::label_number(accuracy = 1)) +
       geom_hline(yintercept = 95, colour = "red", linetype = "dashed") + 
       geom_hline(yintercept = 97, colour = "blue", linetype = "dashed") +
       annotate(geom = "text", x = as.Date("2022-08-01"), y = 94.5, 
                label = "NHS 95% Target", colour = "red") +
       annotate(geom = "text", x = as.Date("2022-08-01"), y = 96.5, 
                label = "2018/2019 Average", colour = "blue")



#})

```


