---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
```


### BEDS

```{r, include=FALSE}
bed_occupancy <- read_csv("Beds by board of treatment and specialty.csv") %>% 
  janitor::clean_names()
```

```{r}
health_boards <- read_csv("health_board_codes.csv") %>% 
  janitor::clean_names()

bed_occupancy <- left_join(bed_occupancy, health_boards, by = "hb")
```

```{r}
bed_occupancy <- bed_occupancy %>% 
  mutate(year = str_sub(quarter, start = 1, end = 4), .after = quarter) %>% 
  mutate(month_num = case_when(
    str_sub(quarter, start = 5, end = 6) == "Q1" ~ 3, 
    str_sub(quarter, start = 5, end = 6) == "Q2" ~ 6, 
    str_sub(quarter, start = 5, end = 6) == "Q3" ~ 9, 
    str_sub(quarter, start = 5, end = 6) == "Q4" ~ 12, 
    ), .after = year
  ) %>% 
  mutate(made_date = make_datetime(year, month_num), .after = month_num)
```

```{r}
# bed occupancy plot
bed_occupancy %>% 
  filter(hb == "S92000003") %>% # Scotland HB
  filter(specialty_name == "All Acute") %>% 
  ggplot() +
  aes(x = made_date, y = percentage_occupancy) +
  geom_line() +
  geom_hline(yintercept = 85, colour = "red") +
  annotate("text", min(bed_occupancy$made_date), 85, vjust = + 2, hjust = 0, 
           label = "85% risk threshold", colour = "red") +
  labs(
    x = "", 
    y = "% occupancy\n", 
    title = "Hospital bed occupancy\n"
  ) + 
   theme_grey()
```


### LENGTH OF STAY

```{r, include=FALSE}
stay_length <- read_csv("Inpatient and day case activity by board of treatment, age and sex.csv") %>% 
  janitor::clean_names()
```

```{r}
stay_length <- stay_length %>% 
  mutate(year = str_sub(quarter, start = 1, end = 4), .after = quarter) %>% 
  mutate(month_num = case_when(
    str_sub(quarter, start = 5, end = 6) == "Q1" ~ 3, 
    str_sub(quarter, start = 5, end = 6) == "Q2" ~ 6, 
    str_sub(quarter, start = 5, end = 6) == "Q3" ~ 9, 
    str_sub(quarter, start = 5, end = 6) == "Q4" ~ 12, 
    ), .after = year
  ) %>% 
  mutate(made_date = make_datetime(year, month_num), .after = month_num)

stay_length
```

```{r}
# average pre-pandemic stay length
stay_length_pre_pandemic_avg <- stay_length %>% 
  filter(year %in% c(2018, 2019)) %>% 
  group_by(hb, month_num, admission_type, age) %>% 
  summarise(average20182019 = mean(average_length_of_stay, na.rm = TRUE))

stay_length_pre_pandemic_avg
```

```{r}
# join average to stay_length file
stay_length <- left_join(stay_length, stay_length_pre_pandemic_avg)
```

```{r}
# summarise for plot of % change to pre-pandemic
stay_length_summ <- stay_length %>% 
  filter(hb == "S92000003") %>% # Scotland HB
  filter(year > 2019) %>% 
  filter(admission_type %in% c("Elective Inpatients", "Emergency Inpatients")) %>% 
  group_by(year, month_num, made_date, admission_type) %>% 
  summarise(avg_stay = sum(average_length_of_stay, na.rm = TRUE), 
            pre_pan_avg = sum(average20182019, na.rm = TRUE)) %>% 
  mutate(pcent_change_to_pre_pan_avg = (avg_stay - pre_pan_avg) / pre_pan_avg * 100)

stay_length_summ
```

```{r}
# plot % change relative to 2018/19 for average stay
stay_length_summ %>% 
  ggplot() +
  aes(x = made_date, y = pcent_change_to_pre_pan_avg, 
      group = admission_type, colour = admission_type) +
  geom_line() +
  scale_y_continuous(limits = c(NA, 20)) +
  labs(
    x = "", 
    y = "% change relative to 2018/19\n", 
    title = "Length of hospital stay (admission type)", 
    colour = NULL
  ) +
   theme_grey()
```

```{r}
# summarise for plot of stay length values by admission type
stay_length_summ <- stay_length %>% 
  filter(hb == "S92000003") %>% # Scotland HB
  filter(admission_type %in% c("Elective Inpatients", "Emergency Inpatients")) %>% 
  group_by(year, month_num, made_date, admission_type) %>% 
  summarise(avg_stay = sum(average_length_of_stay, na.rm = TRUE))
```

```{r}
stay_length_summ %>% 
  ggplot() +
  aes(x = made_date, y = avg_stay, group = admission_type, colour = admission_type) +
  geom_line() +
  labs(
    x = "", 
    y = "average length of hospital stay (days)\n", 
    title = "Length of hospital stay (admission type)", 
    colour = NULL
  ) +
   theme_grey()
```

### LENGTH OF STAY - AGE

```{r}
# summarise for plot of stay length values by age category
stay_length_summ <- stay_length %>% 
  filter(hb == "S92000003") %>% # Scotland HB
  filter(admission_type == "All Inpatients") %>% 
  mutate(age = factor(age, levels = c("90 years and over", "80-89 years", "70-79 years",
                                      "60-69 years", "50-59 years", "40-49 years",
                                      "30-39 years", "20-29 years", "10-19 years", "0-9 years"))) %>% 
  group_by(year, month_num, made_date, age, admission_type) %>% 
  summarise(avg_stay = sum(average_length_of_stay, na.rm = TRUE))
```

```{r}
stay_length_summ %>% 
  ggplot() +
  aes(x = made_date, y = avg_stay, group = age, colour = age) +
  geom_line() +
  labs(
    x = "", 
    y = "average length of hospital stay (days)\n", 
    title = "Length of hospital stay (age of patient)", 
    colour = NULL
  ) +
   theme_grey()
```







